[package]
name = "zerotohero"
version = "0.1.0"
authors = ["peter"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-http = "2.2.0"
actix-service = "2.0.0"
actix-web = "3.3.2"
