name: Rust

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin
    - name: Coverage
      run: cargo tarpaulin --ignore-tests
    - name: lint
      run: cargo clippy -- -D warnings
    - name: formating
      run: cargo fmt -- --check
    - name: install audit
      run: cargo install cargo-audit
    - name: audit
      run: cargo audit
